version: '3.7'
services:
  db:
    image: postgres:12-alpine
    container_name: django-db
    ports:
      - '15432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword1234
      - POSTGRES_DB=testdb
      - DATABASE_HOST=localhost
    volumes:
      - ./db:/var/lib/postgresql/data
  web:
    build: ./web
    container_name: django-web
    tty: true
    volumes:
      - ./web/src:/code
    ports:
      - "18000:8000"
      - "10080:80"
    depends_on:
      - db
    environment:
      # 以下はrun.shがconfig.pyを修正する際に利用
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword1234
      - POSTGRES_DB=testdb
    command: /bin/bash /setting/run.sh 
